import type { Metadata } from "next";
import { Inter, Instrument_Sans, Roboto } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import { ClientProvider } from "./store/StoreProvider";
import Footer from "@/components/UI/Footer";

const inter = Inter({ subsets: ["latin"] });
const instrument_sans = Instrument_Sans({
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "devlinks",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${instrument_sans.className} min-h-[100dvh] min-w-[100vw] bg-lightGrey leading-[150%] text-dark-gray`}
      >
        <ClientProvider>
          <Providers>{children}</Providers>
          <Footer />
        </ClientProvider>
      </body>
    </html>
  );
}
